name: Picodrive 3DS Build

on: workflow_dispatch

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Set up pre-reqs
        run: |
          sudo apt-get install make --version
      - name: install devkitARM and libs
        run: |
          mkdir -p opt/devkitpro
          cd opt/devkitpro
          pwd
          curl "https://wii.leseratte10.de/devkitPro/devkitARM/r45%20%282015%29/devkitARM_r45-x86_64-linux.tar.bz2" --output - |tar xvj
          curl "https://wii.leseratte10.de/devkitPro/libctru/2015/libctru-1.0.0.tar.gz" --output - |tar xvz
          mkdir citro3d-1.0.0
          chdir citro3d-1.0.0
          curl "https://wii.leseratte10.de/devkitPro/other-stuff/citro3d/citro3d-1.0.0.tar.bz2" --output - |tar xvj
          cd ..
          ls -la
          cd ..
          pwd
      - name: build picodrive_3ds
        run: |
          DEVKITPRO=opt/devkitpro
          DEVKITARM=opt/devkitpro/devkitARM
          CTRULIB="opt/devkitpro/libctru-1.0.0 opt/devkitpro/citro3d-1.0.0"
          export DEVKITPRO DEVKITARM CTRULIB
          echo $DEVKITARM
          echo $CTRULIB
          make -f picodrive-make
